services:
  employee-api:
    container_name: employee-api
    image: ${DOCKER_USERNAME}/employee_management:1.0.0
    env_file:
      - .env
    ports:
      - 8888:8888
    networks:
      - spring-demo
networks:
  spring-demo:
    driver: bridge