services:
  employee-api:
    container_name: employee-api
    image: khanhdu01/employee_management:1.0.0
    ports:
      - 8888:8888
    networks:
      - spring-demo
networks:
  spring-demo:
    driver: bridge