spring:
  profiles:
    active: dev
  application:
    name: employee_management
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: jdbc:h2:mem:employee
    driver-class-name: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
application:
  admin:
    default:
      username: ${ADMIN_DEFAULT_USERNAME}
      password: ${ADMIN_DEFAULT_PASSWORD}
server:
  servlet:
    context-path: /
  port: 8888
